-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 09:38:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biscuit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biscuit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biscuit` DEFAULT CHARACTER SET utf8 ;
USE `biscuit` ;

-- -----------------------------------------------------
-- Table `biscuit`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biscuit`.`Utente` (
  `id_utente` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `img_profilo` VARCHAR(45) NOT NULL,
  `data_registrazione` DATETIME NULL,
  PRIMARY KEY (`id_utente`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biscuit`.`Follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biscuit`.`Follow` (
  `id_follow` INT NOT NULL AUTO_INCREMENT,
  `id_utente` INT NOT NULL,
  `id_seguito` INT NOT NULL,
  PRIMARY KEY (`id_follow`),
  INDEX `UserID_Utente_UserID_idx` (`id_utente` ASC) VISIBLE,
  INDEX `FollowingID_Utente_UserID_idx` (`id_seguito` ASC) VISIBLE,
  CONSTRAINT `idUtente_Utente_idUtente`
    FOREIGN KEY (`id_utente`)
    REFERENCES `biscuit`.`Utente` (`id_utente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idSeguito_Utente_idUtente`
    FOREIGN KEY (`id_seguito`)
    REFERENCES `biscuit`.`Utente` (`id_utente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biscuit`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biscuit`.`Post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `id_utente` INT NOT NULL,
  `titolo` VARCHAR(45) NOT NULL,
  `contenuto` VARCHAR(300) NOT NULL,
  `immagine` VARCHAR(45) NULL,
  `data_pubblicazione` DATETIME NULL,
  PRIMARY KEY (`id_post`),
  INDEX `id_user_post_utente_ud_user_idx` (`id_utente` ASC) VISIBLE,
  CONSTRAINT `id_user_post_utente_ud_user`
    FOREIGN KEY (`id_utente`)
    REFERENCES `biscuit`.`Utente` (`id_utente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biscuit`.`Commenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biscuit`.`Commenti` (
  `id_commento` INT NOT NULL,
  `id_post` INT NOT NULL,
  `id_utente_commentatore` INT NOT NULL,
  `testo_commento` VARCHAR(300) NULL,
  `data_commento` DATETIME NULL,
  PRIMARY KEY (`id_commento`),
  INDEX `1_idx` (`id_utente_commentatore` ASC) VISIBLE,
  INDEX `2_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `Fk_utente_com`
    FOREIGN KEY (`id_utente_commentatore`)
    REFERENCES `biscuit`.`Utente` (`id_utente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kf_utente_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `biscuit`.`Post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biscuit`.`PostFavoriti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biscuit`.`PostFavoriti` (
  `id_postFavoriti` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_utente` INT NOT NULL,
  PRIMARY KEY (`id_postFavoriti`),
  INDEX `3_idx` (`id_post` ASC) VISIBLE,
  INDEX `4_idx` (`id_utente` ASC) VISIBLE,
  CONSTRAINT `Fk_PostFavoriti_Post`
    FOREIGN KEY (`id_post`)
    REFERENCES `biscuit`.`Post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fk_PostFavoritiUtente_Utente`
    FOREIGN KEY (`id_utente`)
    REFERENCES `biscuit`.`Utente` (`id_utente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
